### ISSUE TITLE
Consider integrating the "Call for papers" widget of JoindIn.js

### ISSUE THREAD

**Issue by AurelioDeRosa** [joindin/callingallpapers.com#17]
Hi.

This is more a proposal than an issue. A few days ago I released [a new version of JoindIn.js](https://github.com/joindin/JoindIn.js/releases/tag/0.4.0) in which I included [a widget](https://github.com/joindin/JoindIn.js#embedding-the-call-for-papers) inspired to this website that shows the currently open call for papers available on JoindIn. In this page you can see a [demo](http://htmlpreview.github.io/?https://github.com/joindin/JoindIn.js/blob/master/demo/index.html). A few themes are available for the widget.

I was thinking that it might be nice to add it to the website.

**Comment by heiglandreas** [comment]
Well, don't get me wrong, but actually I'm not really sure we need the CfP-widget on the CfP-Site... As that would either mean we don't need the site, or we have the information twice… :wink:

While the widget is pretty cool and I'm currently thinking about creating a Wordpress-Widget out of it for our usergroups website I don't think callingallpapers.com is the right spot.

**Comment by AurelioDeRosa** [comment]
Fair point. I'm closing this issue.
