### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by AurelioDeRosa** [joindin/callingallpapers.com#18]
The website is quite fast already but I think it can be even faster by applying some well-know techniques such as minification and concatenation of the assets. Ideally this could (and should) be automated using a task runner such as Grunt or Gulp. If you want, I can help with this issue.

**Comment by heiglandreas** [comment]
Would ba e great idea. But minification and such stuff should be done during the deployment process. We should speak to @lornajane what possibilities there are.

**Comment by AurelioDeRosa** [comment]
Yes, they are meant to be performed when building the project. I know we're using Jenkins which integrates perfectly with Grunt. So, if you and @lornajane agree I can submit a PR to set up the process. Once done, it'll be a matter of running a couple of commands to deploy a compressed version of the website.

**Comment by lornajane** [comment]
Jenkins probably runs a phing task so feel free to open a PR to change what that task does - make sure you include any platform requirements (I guess node, which we do have on the build server since it runs the frisby tests) as notes in the PR and I can pick it up from there.  Agree that this would be a nice addition :)

**Comment by AurelioDeRosa** [comment]
Looking at the current build file, it seems that Phing executes tasks that can be performed using Node.js on which the former relies anyway. So, I think I can turn them all in Grunt tasks if you agree and we can get rid of Phing.

**Comment by AurelioDeRosa** [comment]
This issue is fixed by #22.

**Comment by AurelioDeRosa** [comment]
This issue has been fixed. Another good improvement will be achieved one #25 is merged.
