### ISSUE TITLE
Call CfPs from Lanyrd

### ISSUE THREAD

**Issue by heiglandreas** [joindin/callingallpapers.com#23]
Check whether Lanyrd contains CfPs and if so call them in

**Comment by AurelioDeRosa** [comment]
This is an interesting idea. Have they published an API?

**Comment by phoenixrises** [comment]
Closest thing I can find seems to be http://lanyrd.com/calls/

**Comment by AurelioDeRosa** [comment]
@phoenixrises I remember that they haven't an API. This will force us to parse the HTML which isn't bulletproof. But I guess this is the best thing we can do.

**Comment by phoenixrises** [comment]
@AurelioDeRosa Indeed, it's unfortunate, but at least we should be able to do _something_ with it.

**Comment by heiglandreas** [comment]
As far as I figured out Lanyrd are talking about creating an API for at least three years by now. Nothing happened until now though. But they seem to have a way to track certain things with a calendar-file. Not sure though how to get that information...
