### ISSUE TITLE
Domain expiring soon

### ISSUE THREAD

**Issue by lornajane** [joindin/callingallpapers.com#52]
Just checking that you've seen the domain expiry reminder emails for callingallpapers.com

**Comment by heiglandreas** [comment]
Thanks! They actually didn't get through to me. I now need to check why....

Though the domain is renewed.

**Comment by heiglandreas** [comment]
The domain contact is set to info@joind.in and I don't get those emails ;-)

**Comment by lornajane** [comment]
As long as it did get renewed, we got the 14 day warning about 10 days ago :+1:
